### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by jcarson** [fabiobeoni/adapt-animation-frame#1]
Do you offer a version of this plugin that is compatible with 2.0.17?

Error: This plugin is incompatible with version v2.0.17 of the Adapt framework

**Comment by fabiobeoni** [comment]
Hi, thanks for asking.

I keep all my plugins updated to the latest framework version, by the way if you want to use it with the v2.x you do as follow:

1. download the ZIP file of the plugin
2. double click on it, reach the file "bower.json" and open it
3. change this line of text `"framework": "^3.0.0"` with `"framework": "^2.0.0"`
4. save the file

If you prefer you can also unzip the plugin, make the changes and zip it again. If you that, make sure your zip folder structure has single main folder into it.

Let me know ;), cheers.

**Comment by jcarson** [comment]
After changing the bower.json like you suggested it did import (yeah), however I have yet to get a oam to function and then realized you have a pull request out for that. (*excitedly*) Any idea when that might happen?

This is awesome by the way, I tested this with some sample animations from animate cc by embedding and linking externally the html and they all appeared/functioned as intended.

The only issue I see is that the container does not resize once opened. The content is responsive but a user would have to refresh the browser to actually change the height of the container holding the content. Not a deal breaker by any means and not sure how one might go adjusting that for a truly responsive experience but this plugin is good nonetheless.  My two cents, this needs to become part of the adapt framework component arsenal immediately. Great work! Cheers.
